apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: instana-agent
spec:
  zone:
    name: demo-zone
  cluster:
      name: itz-jem4wu.infra01-lb.fra02.techzone.ibm.com
  agent:
    key: UE1az4ZZRqSpyw7NcBMWhw
    downloadKey: UE1az4ZZRqSpyw7NcBMWhw
    endpointHost: ingress-red-saas.instana.io
    endpointPort: "443"
